### ISSUE TITLE
TypeError when running cityscapes_panoptic_converter.py

### ISSUE THREAD

**Issue by Ynzl** [cocodataset/panopticapi#17]
I get a TypeError when trying to run the cityscapes converter.

The problem seems to be that something is using a numpy type which can't be serialized by the json module.

```
Traceback (most recent call last):
  File "cityscapes_gt_converter/cityscapes_panoptic_converter.py", line 119, in <module>
    panoptic_converter(original_format_folder, out_folder, out_file)
  File "cityscapes_gt_converter/cityscapes_panoptic_converter.py", line 116, in panoptic_converter
    json.dump(d, f)
  File "/export/home/yuyanli/.local/opt/miniconda3/envs/t4/lib/python3.6/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/export/home/yuyanli/.local/opt/miniconda3/envs/t4/lib/python3.6/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/export/home/yuyanli/.local/opt/miniconda3/envs/t4/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/export/home/yuyanli/.local/opt/miniconda3/envs/t4/lib/python3.6/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/export/home/yuyanli/.local/opt/miniconda3/envs/t4/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/export/home/yuyanli/.local/opt/miniconda3/envs/t4/lib/python3.6/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/export/home/yuyanli/.local/opt/miniconda3/envs/t4/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/export/home/yuyanli/.local/opt/miniconda3/envs/t4/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/export/home/yuyanli/.local/opt/miniconda3/envs/t4/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'int64' is not JSON serializable
```

P.S. I also had to change `from utils import IdGenerator` to `from panopticapi.utils import IdGenerator`

**Comment by alexander-kirillov** [comment]
This error should be fixed now. Can you try it again?

**Comment by mitalbert** [comment]
@alexander-kirillov I have the same issue.

> 470 500
> 480 500
> 490 500
> Traceback (most recent call last):
>   File "cityscapes_gt_converter/cityscapes_panoptic_converter.py", line 119, in <module>
>     panoptic_converter(original_format_folder, out_folder, out_file)
>   File "cityscapes_gt_converter/cityscapes_panoptic_converter.py", line 116, in panoptic_converter
>     save_json(d, out_file)
>   File "/home/user/.local/lib/python3.7/site-packages/panopticapi/utils.py", line 99, in save_json
>     json.dump(d, f)
>   File "/usr/lib/python3.7/json/__init__.py", line 179, in dump
>     for chunk in iterable:
>   File "/usr/lib/python3.7/json/encoder.py", line 431, in _iterencode
>     yield from _iterencode_dict(o, _current_indent_level)
>   File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
>     yield from chunks
>   File "/usr/lib/python3.7/json/encoder.py", line 325, in _iterencode_list
>     yield from chunks
>   File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
>     yield from chunks
>   File "/usr/lib/python3.7/json/encoder.py", line 325, in _iterencode_list
>     yield from chunks
>   File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
>     yield from chunks
>   File "/usr/lib/python3.7/json/encoder.py", line 438, in _iterencode
>     o = _default(o)
>   File "/usr/lib/python3.7/json/encoder.py", line 179, in default
>     raise TypeError(f'Object of type {o.__class__.__name__} '
> TypeError: Object of type int64 is not JSON serializable


The output json files contains all images till {"id": "munster_000173_000019", "width": 2048, "height": 1024, "file_name": "munster_000173_000019_leftImg8bit.png"}], and the first attempt of annotations:

> ... "annotations": [{"image_id": "frankfurt_000000_000294", "file_name": "frankfurt_000000_000294_gtFine_instanceIds.png", "segments_info": [{"id": 8405120, "category_id": 7, "area":

**Comment by mitalbert** [comment]
I fixed it by converting to python integer.

Added the

`bbox = [x, y, width, height];
 int_bbox = [int(value) for value in bbox]`

And changed "area": area, to
`"area": int(area),`

**Comment by zhangliyun9120** [comment]
@alexander-kirillov 
Sorry, it seems the bug is still there:
Traceback (most recent call last):
  File "converters/detection2panoptic_coco_format.py", line 151, in <module>
    args.categories_json_file)
  File "converters/detection2panoptic_coco_format.py", line 124, in convert_detection_to_panoptic_coco_format
    save_json(d_coco, output_json_file)
  File "/home/liyun/anaconda3/envs/detectron2/lib/python3.6/site-packages/panopticapi/utils.py", line 99, in save_json
    json.dump(d, f)
  File "/home/liyun/anaconda3/envs/detectron2/lib/python3.6/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/home/liyun/anaconda3/envs/detectron2/lib/python3.6/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/home/liyun/anaconda3/envs/detectron2/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/home/liyun/anaconda3/envs/detectron2/lib/python3.6/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/home/liyun/anaconda3/envs/detectron2/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/home/liyun/anaconda3/envs/detectron2/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/home/liyun/anaconda3/envs/detectron2/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'int64' is not JSON serializable

how can I fixed that?
thank you.

**Comment by zhangliyun9120** [comment]
@Yuyan-Li 

I found a solution here: 

https://blog.csdn.net/Zhou_yongzhe/article/details/87692052

tested ok!

pls refer to that.
